import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
live_config_reload = true

[window]
decorations = "none"
opacity = 0.7
blur = true

[font]
normal = { family = "CaskaydiaCove NF", style = "Regular" }
size = 14
